const courseExitSurveyHeader = [
  { id: "_id", title: "Key" },
  { id: "courseCode", title: "Course Code" },
  { id: "courseName", title: "Course Name" },
  { id: "year", title: "Year" },
  { id: "CO1", title: "CO1" },
  { id: "CO2", title: "CO2" },
  { id: "CO3", title: "CO3" },
  { id: "CO4", title: "CO4" },
  { id: "CO5", title: "CO5" },
  { id: "CO6", title: "CO6" },
  { id: "CO7", title: "CO7" },
  { id: "CO8", title: "CO8" },
  {
    id: "appropriatenessOfAssessmentToolsUsed",
    title: "Appropriateness Of Assessment Tools",
  },
  { id: "courseSuggestions", title: "Course Suggestions" },
  { id: "like", title: "Like" },
  { id: "dislike", title: "Dislike" },
  { id: "hostingTools", title: "Hosting Tools" },
  { id: "lectureRating", title: "Lecture Rating" },
  { id: "textBookAvailability", title: "Text Book Availability" },
];

const parentsFeedbackHeader = [
  { id: "_id", title: "Key" },
  { id: "studentName", title: "Student Name" },
  { id: "parentName", title: "Parent Name" },
  { id: "mobile", title: "Mobile" },
  { id: "parentOccupation", title: "Parent Occupation" },
  { id: "ParentsSuggestions", title: "Parents Suggestions" },
  { id: "date", title: "Date" },
  { id: "expectations", title: "Expectations" },
  { id: "fulfill", title: "Fulfill" },
  { id: "reasons", title: "Reasons" },
];

const employerFeedbackHeader = [
  { id: "_id", title: "Key" },
  { id: "organizationName", title: "Organization Name" },
  { id: "organizationLocation", title: "Organization Location" },
  { id: "feedbackProvider", title: "Feedback Provider" },
  { id: "feedbackProviderDesignation", title: "Feedback Provider Designation" },
  { id: "alumnusName", title: "Alumnus Name" },
  { id: "natureOfalumnusRole", title: "Nature of Alumnus Role" },
  { id: "alumnusRole", title: "Alumnus Role" },
  { id: "qualityOfWork", title: "Quality of Work" },
  { id: "individualAndTeamWork", title: "Individual and Teamwork" },
  { id: "technicalKnowledge", title: "Technical Knowlodge" },
  { id: "domainKnowledge", title: "Domain Knowledge" },
  { id: "overallRating", title: "Overall Rating" },
  { id: "suggestions", title: "Suggestions" },
  { id: "digitalSignature", title: "Digital Signatures" },
];