module.exports.jsonFormater = (rowData, type) => {
  var format = {};

  if (type === "courseExitSurvey") {
    format = {
      _id: rowData["Key"],
      courseCode: rowData["Course Code"],
      courseName: rowData["Course Name"],
      year: rowData["Year"],
      CO1: rowData["CO1"],
      CO2: rowData["CO2"],
      CO3: rowData["CO3"],
      CO4: rowData["CO4"],
      CO5: rowData["CO5"],
      CO6: rowData["CO6"],
      CO7: rowData["CO7"],
      CO8: rowData["CO8"],
      appropriatenessOfAssessmentToolsUsed:
        rowData["Appropriateness Of Assessment Tools"],
      courseSuggestions: rowData["Course Suggestions"],
      like: rowData["Like"],
      dislike: rowData["Dislike"],
      hostingTools: rowData["Hosting Tools"],
      lectureRating: rowData["Lecture Rating"],
      textBookAvailability: rowData["Text Book Availability"],
    };
  } else if (type === "parentsFeedback") {
    format = {
      _id: rowData["Key"],
      studentName: rowData["Student Name"],
      parentName: rowData["Parent Name"],
      mobile: rowData["Mobile"],
      parentOccupation: rowData["Parent Occupation"],
      ParentsSuggestions: rowData["Parents Suggestions"],
      date: rowData["Date"],
      expectations: rowData["Expectations"],
      fulfill: rowData["Fulfill"],
      reasons: rowData["Reasons"],
    };
  } else if (type === "employerFeedback") {
    format = {
      _id: ["Key"],
      organizationName: ["Organization Name"],
      organizationLocation: ["Organization Location"],
      feedbackProvider: ["Feedback Provider"],
      feedbackProviderDesignation: ["Feedback Provider Designation"],
      alumnusName: ["Alumnus Name"],
      natureOfalumnusRole: ["Nature of Alumnus Role"],
      alumnusRole: ["Alumnus Role"],
      qualityOfWork: ["Quality of Work"],
      individualAndTeamWork: ["Individual and Teamwork"],
      technicalKnowledge: ["Technical Knowlodge"],
      domainKnowledge: ["Domain Knowledge"],
      overallRating: ["Overall Rating"],
      suggestions: ["Suggestions"],
      digitalSignature: ["Digital Signatures"],
    };
  } else if (type === "facultyFeedback") {
    format = {
      _id: ["Key"],
      academicYear: ["Academic Year"],
      addContents: ["Add Contents"],
      assessmentMethods: ["Assessment Methods"],
      challengingTopics: ["Challenging Topics"],
      courseCode: ["Course Code"],
      courseName: ["Course Name"],
      courseOutcomesAppropriateness: ["Course Outcomes Appropriateness"],
      designThinkingContribution: ["Design Thinking Contribution"],
      industryAndSocietalNeeds: ["Industry And Societal Needs"],
      innovativeTeachingMethods: ["Innovative Teaching Methods"],
      removeContents: ["Remove Contents"],
      semester: ["Semester"],
      studentProficiencyInPrerequisites: [
        "Student Proficiency In Prerequisites",
      ],
      suggestions: ["Suggestions"],
      timeForEffectiveCoverage: ["Time For Effective Coverage"],
      courseFacilitator: ["Course Facilitator"],
    };
  } else if (type === "peerFeedback") {
    format = {
      _id: ["Key"],
      designation: ["Designation"],
      expert: ["Expert"],
      generalFeedback: ["General Feedback"],
      name: ["Name"],
      organizationName: ["Organization Name"],
      suggestions: ["Suggestions"],
    };
  } else if (type === "recruitersFeedback") {
    format = {
      _id: ["Key"],
      communication: ["Communication"],
      contemporaryKnowledge: ["Contemporary Knowledge"],
      criticalThinking: ["Critical Thinking"],
      design: ["Design"],
      designation: ["Designation"],
      email: ["Email"],
      exposureToIt: ["Exposure To It"],
      interpersonal: ["Interpersonal"],
      knowledge: ["Knowledge"],
      knowledgeAboutSPD: ["Knowledge About SPD"],
      leadership: ["Leadership"],
      lifeSkills: ["Life Skills"],
      name: ["Name"],
      organisationName: ["Organisation Name"],
      overallRating: ["Overall Rating"],
      problemSolving: ["Problem Solving"],
      professionalEthics: ["Professional Ethics"],
      programmingSkill: ["Programming Skill"],
      projectManagementSkills: ["ProjectManagement Skills"],
      suggestions: ["Suggestions"],
      systemEngineeringSkills: ["System Engineering Skills"],
      team: ["Team"],
    };
  } else if (type === "graduateExitSurvey") {
    format = {
      _id: ["Key"],
      name: ["name"],
      regNo: ["regNo"],
      yearJoined: ["yearJoined"],
      email: ["email"],
      mobileNo: ["mobileNo"],
      presentAddress: ["presentAddress"],
      educationalExperience: ["educationalExperience"],
      effectiveness: ["effectiveness"],
      adminOffices: ["adminOffices"],
      careerGuidanceAndPlacement: ["careerGuidanceAndPlacement"],
      transportation: ["transportation"],
      canteen: ["canteen"],
      hostel: ["hostel"],
      availability: ["availability"],
      contactHoursOutsideLecturing: ["contactHoursOutsideLecturing"],
      professionalism: ["professionalism"],
      presentation: ["presentation"],
      mentoring: ["mentoring"],
      centralLibrary: ["centralLibrary"],
      departnmentLibrary: ["departnmentLibrary"],
      centralComputingCentre: ["centralComputingCentre"],
      infrastructuresAndLabs: ["infrastructuresAndLabs"],
      internet: ["internet"],
      parking: ["parking"],
      modernClassroom: ["modernClassroom"],
      curriculum: ["curriculum"],
      syllabiContent: ["syllabiContent"],
      studentLearningAssessment: ["studentLearningAssessment"],
      qualityOfInstruction: ["qualityOfInstruction"],
      opportunityForCreativity: ["opportunityForCreativity"],
      knowledgeAndEthics: ["knowledgeAndEthics"],
      teamWork: ["teamWork"],
      demonstrateLeadership: ["demonstrateLeadership"],
      interpersonalSkillsDevelopment: ["interpersonalSkillsDevelopment"],
      lifeSkills: ["lifeSkills"],
      verbalCommunication: ["verbalCommunication"],
      writtenCommunication: ["writtenCommunication"],
      problemSolving: ["problemSolving"],
      criticalThinking: ["criticalThinking"],
      researchSkills: ["researchSkills"],
      programmingSkills: ["programmingSkills"],
      productDevelopment: ["productDevelopment"],
      applyingSkillsInFinalYearProject: ["applyingSkillsInFinalYearProject"],
      comfortableAtHighlevelLanguage: ["comfortableAtHighlevelLanguage"],
      comfortableInConfiguringSystems: ["comfortableInConfiguringSystems"],
      exposureToSocietyRelevantProjects: ["exposureToSocietyRelevantProjects"],
      knowledgeOfpersonalHealtheErgonomics: [
        "knowledgeOfpersonalHealtheErgonomics",
      ],
      knowledgeOfSoftwareCopyright: ["knowledgeOfSoftwareCopyright"],
      NSSorNCCCamps: ["NSSorNCCCamps"],
      exposureToImpactOfICTsolution: ["exposureToImpactOfICTsolution"],
      emphasisOnSDofICTsolutions: ["emphasisOnSDofICTsolutions"],
      abilityInExecutingFinalYearProject: [
        "abilityInExecutingFinalYearProject",
      ],
      organizingAndManagingEvents: ["organizingAndManagingEvents"],
      numberOfPapersPublished: ["numberOfPapersPublished"],
      publicationDetails: ["publicationDetails"],
      numberOfSoftwaresorProductsDeveloped: [
        "numberOfSoftwaresorProductsDeveloped",
      ],
      projectDetails: ["projectDetails"],
      membershipInProfessionalSocieties: ["membershipInProfessionalSocieties"],
      numberOfInternationalCertifications: [
        "numberOfInternationalCertifications",
      ],
      certificationDetails: ["certificationDetails"],
      overallRating: ["overallRating"],
      comment: ["comment"],
      roleYouWishToContribute: ["roleYouWishToContribute"],
      collegeName: ["collegeName"],
      degree: ["degree"],
      discipline: ["discipline"],
      admissionYear: ["admissionYear"],
      workforceName: ["workforceName"],
      workforceSector: ["workforceSector"],
      workforceDesignation: ["workforceDesignation"],
      workforceCity: ["workforceCity"],
      workforceSalaryPerAnnum: ["workforceSalaryPerAnnum"],
      parttimeCollegeName: ["parttimeCollegeName"],
      parttimeDegree: ["parttimeDegree"],
      parttimeDiscipline: ["parttimeDiscipline"],
      parttimeAdmissionYear: ["parttimeAdmissionYear"],
      parttimeWorkforceName: ["parttimeWorkforceName"],
      sector: ["sector"],
      designation: ["designation"],
      city: ["city"],
      salaryPerAnnum: ["salaryPerAnnum"],
      onlineExam: ["onlineExam"],
      GREScore: ["GREScore"],
      GMATScore: ["GMATScore"],
      CATScore: ["CATScore"],
      GATEScore: ["GATEScore"],
    };
  } else if (type === "alumniFeedback") {
    format = {
      _id: ["Key"],
      name: ["name"],
      degree: ["degree"],
      yearOfGraduation: ["yearOfGraduation"],
      email: ["email"],
      address: ["address"],
      workingOrganisationName: ["workingOrganisationName"],
      designation: ["designation"],
      annualSalary: ["annualSalary"],
      yearsWorkingInTheCompany: ["yearsWorkingInTheCompany"],
      date: ["date"],
      natureOfWork: ["natureOfWork"],
      roles: ["roles"],
      problemSolvingSkills: ["problemSolvingSkills"],
      universityName: ["universityName"],
      higherDegree: ["higherDegree"],
      admissionYear: ["admissionYear"],
      graduationYear: ["graduationYear"],
      ownOrganizationName: ["ownOrganizationName"],
      buisnessAndTechnicalDomain: ["buisnessAndTechnicalDomain"],
      ownCompanyStartedYear: ["ownCompanyStartedYear"],
      websiteUrl: ["websiteUrl"],
      numberOfAwards: ["numberOfAwards"],
      awardDetails: ["awardDetails"],
      noOfPapersPublishedAfterUG: ["noOfPapersPublishedAfterUG"],
      publicationDetails: ["publicationDetails"],
      noOfInternationalCertifications: ["noOfInternationalCertifications"],
      certificationDetails: ["certificationDetails"],
      noOfPatentsFiled: ["noOfPatentsFiled"],
      patentDetails: ["patentDetails"],
      membership: ["membership"],
      higherOfficialName: ["higherOfficialName"],
      higherOfficialDesignation: ["higherOfficialDesignation"],
      higherOfficialMailID: ["higherOfficialMailID"],
      overallRatingCollege: ["overallRatingCollege"],
      strngthOrWeaknessInTheProgram: ["strngthOrWeaknessInTheProgram"],
      roleWishToContribute: ["roleWishToContribute"],
    };
  }

  return format;
};
